version: "3.8"
services:
  carpooling-api-database:
    image: mysql:8.4.0
    restart: unless-stopped
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=************
      - MYSQL_DATABASE=carpooling
      - MYSQL_USER=gatewayuser
      - MYSQL_PASSWORD=password
    volumes:
      - ./dbdata:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - mobbscan-network         # <-- Aquí añadí la red

  api:
    build: .
    container_name: carpooling-user
    ports:
      - "8081:8080"              # <-- Aquí corregí el puerto para que coincida con application.yml
    depends_on:
      - carpooling-api-database
    environment:
      - MONGODB_URI=${SPRING_DATA_MONGODB_URI}
      - MOBBSCAN_API_KEY=${MOBBSCAN_API_KEY}
      - SPRING_DATASOURCE_USERNAME=gatewayuser
      - SPRING_DATASOURCE_PASSWORD=password
      - MOBBSCAN_API_SECRET=${MOBBSCAN_API_SECRET}
      - MOBBSCAN_API_GATEWAY=${MOBBSCAN_API_GATEWAY}
    networks:
      - mobbscan-network

networks:
  mobbscan-network:
    driver: bridge